apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-container
        image: aymanmostafa/auth-srv:0.0.5-SNAPSHOT
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: "dev"
         - name: SPRING_CONFIG_NAME
           value: "application"        
         - name: SPRING_CONFIG_LOCATION
           value: file:/opt/config/
        envFrom:
         - secretRef:
             name: db-secret
        ports:
         - containerPort: 8080
        ports:
         - containerPort: 8080
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 20
          successThreshold: 1
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1 
        volumeMounts:
        - name: config-volume
          mountPath: /opt/config
      volumes:
      - name: config-volume
        configMap:
          name: auth-srv-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
      app: auth-app
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30010